### ISSUE TITLE
How to import scheme?

### ISSUE THREAD

**Issue by matt-senseye** [kirsanium/TerminalColors#1]
The description says `this plugin adds a new "Import console color scheme" button to the scheme importing menu` - please could you clarify where I can find the scheme importing menu? I tried importing the file in `Preferences -> Editor -> Color Scheme` but I get this error:

`Import failed: <path>.itermcolors is not a valid scheme. Scheme 'name' attribute is missing`

Am I looking in the wrong place? Thanks

**Comment by sarahsturgeon** [comment]
Getting the same thing. The plugin suggests there should be a new entry in the "import" menu for "import console", but I don't see it. I think it's just outdated.

**Comment by kirsanium** [comment]
@matt-senseye @brandonsturgeon 
I might be a little bit late on this issue, but I have updated the plugin, so it's working now! You can still find it under the name of "TerminalColors" on JetBrains Marketplace. Please, try it out and let me know if something goes wrong.
